- name: Create Instances
  hosts: localhost
  gather_facts: False

  tasks:
      ec2:
         key_name: key
         group: test
         instance_type: t2.micro
         image: "{{ ami-092391a11f8aa4b7b }}"
         wait: true
         exact_count: 2
         count_tag:
            Name: warhello
         instance_tags:
            Name: warhello
      register: ec2