---
- name: Create Instances
  tasks:
    - name: Create compile machine
      ec2:
        key_name: key
        instance_type: t2.micro
        image: ami-092391a11f8aa4b7b
        wait: yes
        group: compile
        count: 1
        vpc_subnet_id: subnet-group
        assign_public_ip: yes

    - name: Create prod machine
      ec2:
        key_name: key
        instance_type: t2.micro
        image: ami-092391a11f8aa4b7b
        wait: yes
        group: compile
        count: 1
        vpc_subnet_id: subnet-group
        assign_public_ip: yes